export enum abbreviations {
    "bv" = "bijvoorbeeld",
    "tbv" = "ten behoeve van",
    "vb" = "bijvoorbeeld",
    "bvb" = "bijvoorbeeld",
    "ve" = "van een",
    "vd" = "van de",
    "vh" = "van het",
    "ttz" = "het is te zeggen",
    "incl" = "inclusief",
    "eg" = "bijvoorbeeld",
    "ie" = "Met andere woorden",
    "oa" = "onder andere",
    "mbv" = "met behulp van",
    "dmv" = "door middel van",
    "ed" = "en dergelijke",
    "tgv" = "ten gevolge van",
    "ihkv" = "in het kader van",
    "evt" = "eventueel",
    "ih" = "in het",
}