name: Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version:
          - 14.x
          - 16.x
          - 18.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npx lerna exec -- npm i
          npx lerna bootstrap
      - name: Build project
        run: npm run build
