name: Integration tests
on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version:
          - 14.x
          - 16.x
          - 18.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
          npx lerna exec -- npm i
          npx lerna bootstrap
      - name: Build project
        run: npm run build
      - name: Run integration test script
        run: ./.github/scripts/oslo-converter-uml-ea.int.sh
        shell: bash